FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY chatbot_service.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD uvicorn chatbot_service:app --reload --host 0.0.0.0 --port 8000 || true && tail -f /dev/null