services:
  vector-builder:
    profiles:
      - vb
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile-vector_builder
    volumes:
      - ./data:/app/data
    container_name: vector_builder
    
  chatbot-service:
    profiles:
      - chatbot
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile-chatbot
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    container_name: chatbot